ai_engines:
  allowed_engines:
  - gemini
  - local
  compliance_mode: false
  cost_optimization: true
  cost_preferences:
    free: local
    high_cost: claude
    low_cost: web_search
    medium_cost: gemini
  default_engine: gemini
  task_routing:
    code_analysis: gemini
    code_generation: cursor
    document_generation: claude
    git_operations: local
    shell_operations: local
    web_browsing: web_browser
    web_search: web_search
current_project: final_test_project
cursor:
  api_url: http://localhost:5000
  code_generation: true
  max_tokens: 4000
  path: cursor  # macOS: /Applications/Cursor.app/Contents/Resources/app/bin/cursor
  temperature: 0.1
gemini:
  max_tokens: 4000
  temperature: 0.1
llm:
  max_tokens: 4000
  model_name: claude-sonnet-4-5-20250929
  provider: anthropic
  temperature: 0.1
projects_root_dir: projects
script_output_dir: generated_scripts
