ai_engines:
  allowed_engines:
  - claude
  - gemini
  - cursor
  - web_search
  - web_browser
  - local
  compliance_mode: false
  cost_optimization: true
  cost_preferences:
    free: local
    high_cost: claude
    low_cost: web_search
    medium_cost: gemini
  default_engine: gemini
  task_routing:
    code_analysis: gemini
    code_generation: cursor
    document_generation: gemini
    git_operations: local
    shell_operations: local
    web_browsing: web_browser
    web_search: web_search
current_project: test_project
cursor:
  api_url: http://localhost:5000
  code_generation: true
  max_tokens: 4000
  path: cursor
  temperature: 0.1
gemini:
  max_tokens: 4000
  temperature: 0.1
llm:
  max_tokens: 4000
  model_name: claude-sonnet-4-5-20250929
  provider: anthropic
  temperature: 0.1
projects_root_dir: projects
